/*
Boost API

This is a REST API of the Boost App.

API version: 0.0.1-beta1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
)

// AddNewsRelationshipsAuthor Author of the news.
type AddNewsRelationshipsAuthor struct {
	Data *RelatedEntity `json:"data,omitempty"`
}

// NewAddNewsRelationshipsAuthor instantiates a new AddNewsRelationshipsAuthor object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddNewsRelationshipsAuthor() *AddNewsRelationshipsAuthor {
	this := AddNewsRelationshipsAuthor{}
	return &this
}

// NewAddNewsRelationshipsAuthorWithDefaults instantiates a new AddNewsRelationshipsAuthor object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddNewsRelationshipsAuthorWithDefaults() *AddNewsRelationshipsAuthor {
	this := AddNewsRelationshipsAuthor{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *AddNewsRelationshipsAuthor) GetData() RelatedEntity {
	if o == nil || o.Data == nil {
		var ret RelatedEntity
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddNewsRelationshipsAuthor) GetDataOk() (*RelatedEntity, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *AddNewsRelationshipsAuthor) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given RelatedEntity and assigns it to the Data field.
func (o *AddNewsRelationshipsAuthor) SetData(v RelatedEntity) {
	o.Data = &v
}

func (o AddNewsRelationshipsAuthor) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableAddNewsRelationshipsAuthor struct {
	value *AddNewsRelationshipsAuthor
	isSet bool
}

func (v NullableAddNewsRelationshipsAuthor) Get() *AddNewsRelationshipsAuthor {
	return v.value
}

func (v *NullableAddNewsRelationshipsAuthor) Set(val *AddNewsRelationshipsAuthor) {
	v.value = val
	v.isSet = true
}

func (v NullableAddNewsRelationshipsAuthor) IsSet() bool {
	return v.isSet
}

func (v *NullableAddNewsRelationshipsAuthor) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddNewsRelationshipsAuthor(val *AddNewsRelationshipsAuthor) *NullableAddNewsRelationshipsAuthor {
	return &NullableAddNewsRelationshipsAuthor{value: val, isSet: true}
}

func (v NullableAddNewsRelationshipsAuthor) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddNewsRelationshipsAuthor) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
