/*
Boost API

This is a REST API of the Boost App.

API version: 0.0.1-beta1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
)

// AuthPostRequest struct for AuthPostRequest
type AuthPostRequest struct {
	Data Credentials `json:"data"`
}

// NewAuthPostRequest instantiates a new AuthPostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthPostRequest(data Credentials) *AuthPostRequest {
	this := AuthPostRequest{}
	this.Data = data
	return &this
}

// NewAuthPostRequestWithDefaults instantiates a new AuthPostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthPostRequestWithDefaults() *AuthPostRequest {
	this := AuthPostRequest{}
	return &this
}

// GetData returns the Data field value
func (o *AuthPostRequest) GetData() Credentials {
	if o == nil {
		var ret Credentials
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *AuthPostRequest) GetDataOk() (*Credentials, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *AuthPostRequest) SetData(v Credentials) {
	o.Data = v
}

func (o AuthPostRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableAuthPostRequest struct {
	value *AuthPostRequest
	isSet bool
}

func (v NullableAuthPostRequest) Get() *AuthPostRequest {
	return v.value
}

func (v *NullableAuthPostRequest) Set(val *AuthPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthPostRequest(val *AuthPostRequest) *NullableAuthPostRequest {
	return &NullableAuthPostRequest{value: val, isSet: true}
}

func (v NullableAuthPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
