/*
Boost API

This is a REST API of the Boost App.

API version: 0.0.1-beta1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
)

// AddPhoneRelationships struct for AddPhoneRelationships
type AddPhoneRelationships struct {
	User AddPhoneRelationshipsUser `json:"user"`
}

// NewAddPhoneRelationships instantiates a new AddPhoneRelationships object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddPhoneRelationships(user AddPhoneRelationshipsUser) *AddPhoneRelationships {
	this := AddPhoneRelationships{}
	this.User = user
	return &this
}

// NewAddPhoneRelationshipsWithDefaults instantiates a new AddPhoneRelationships object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddPhoneRelationshipsWithDefaults() *AddPhoneRelationships {
	this := AddPhoneRelationships{}
	return &this
}

// GetUser returns the User field value
func (o *AddPhoneRelationships) GetUser() AddPhoneRelationshipsUser {
	if o == nil {
		var ret AddPhoneRelationshipsUser
		return ret
	}

	return o.User
}

// GetUserOk returns a tuple with the User field value
// and a boolean to check if the value has been set.
func (o *AddPhoneRelationships) GetUserOk() (*AddPhoneRelationshipsUser, bool) {
	if o == nil {
		return nil, false
	}
	return &o.User, true
}

// SetUser sets field value
func (o *AddPhoneRelationships) SetUser(v AddPhoneRelationshipsUser) {
	o.User = v
}

func (o AddPhoneRelationships) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["user"] = o.User
	}
	return json.Marshal(toSerialize)
}

type NullableAddPhoneRelationships struct {
	value *AddPhoneRelationships
	isSet bool
}

func (v NullableAddPhoneRelationships) Get() *AddPhoneRelationships {
	return v.value
}

func (v *NullableAddPhoneRelationships) Set(val *AddPhoneRelationships) {
	v.value = val
	v.isSet = true
}

func (v NullableAddPhoneRelationships) IsSet() bool {
	return v.isSet
}

func (v *NullableAddPhoneRelationships) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddPhoneRelationships(val *AddPhoneRelationships) *NullableAddPhoneRelationships {
	return &NullableAddPhoneRelationships{value: val, isSet: true}
}

func (v NullableAddPhoneRelationships) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddPhoneRelationships) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
