/*
Boost API

This is a REST API of the Boost App.

API version: 0.0.1-beta1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
)

// NewsAddPost401Response struct for NewsAddPost401Response
type NewsAddPost401Response struct {
	Error *NewsAddPost401ResponseError `json:"error,omitempty"`
}

// NewNewsAddPost401Response instantiates a new NewsAddPost401Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNewsAddPost401Response() *NewsAddPost401Response {
	this := NewsAddPost401Response{}
	return &this
}

// NewNewsAddPost401ResponseWithDefaults instantiates a new NewsAddPost401Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNewsAddPost401ResponseWithDefaults() *NewsAddPost401Response {
	this := NewsAddPost401Response{}
	return &this
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *NewsAddPost401Response) GetError() NewsAddPost401ResponseError {
	if o == nil || o.Error == nil {
		var ret NewsAddPost401ResponseError
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NewsAddPost401Response) GetErrorOk() (*NewsAddPost401ResponseError, bool) {
	if o == nil || o.Error == nil {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *NewsAddPost401Response) HasError() bool {
	if o != nil && o.Error != nil {
		return true
	}

	return false
}

// SetError gets a reference to the given NewsAddPost401ResponseError and assigns it to the Error field.
func (o *NewsAddPost401Response) SetError(v NewsAddPost401ResponseError) {
	o.Error = &v
}

func (o NewsAddPost401Response) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Error != nil {
		toSerialize["error"] = o.Error
	}
	return json.Marshal(toSerialize)
}

type NullableNewsAddPost401Response struct {
	value *NewsAddPost401Response
	isSet bool
}

func (v NullableNewsAddPost401Response) Get() *NewsAddPost401Response {
	return v.value
}

func (v *NullableNewsAddPost401Response) Set(val *NewsAddPost401Response) {
	v.value = val
	v.isSet = true
}

func (v NullableNewsAddPost401Response) IsSet() bool {
	return v.isSet
}

func (v *NullableNewsAddPost401Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNewsAddPost401Response(val *NewsAddPost401Response) *NullableNewsAddPost401Response {
	return &NullableNewsAddPost401Response{value: val, isSet: true}
}

func (v NullableNewsAddPost401Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNewsAddPost401Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
