/*
Boost API

This is a REST API of the Boost App.

API version: 0.0.1-beta1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
)

// NewsGet401Response struct for NewsGet401Response
type NewsGet401Response struct {
	Error *NewsGet401ResponseError `json:"error,omitempty"`
}

// NewNewsGet401Response instantiates a new NewsGet401Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNewsGet401Response() *NewsGet401Response {
	this := NewsGet401Response{}
	return &this
}

// NewNewsGet401ResponseWithDefaults instantiates a new NewsGet401Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNewsGet401ResponseWithDefaults() *NewsGet401Response {
	this := NewsGet401Response{}
	return &this
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *NewsGet401Response) GetError() NewsGet401ResponseError {
	if o == nil || o.Error == nil {
		var ret NewsGet401ResponseError
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NewsGet401Response) GetErrorOk() (*NewsGet401ResponseError, bool) {
	if o == nil || o.Error == nil {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *NewsGet401Response) HasError() bool {
	if o != nil && o.Error != nil {
		return true
	}

	return false
}

// SetError gets a reference to the given NewsGet401ResponseError and assigns it to the Error field.
func (o *NewsGet401Response) SetError(v NewsGet401ResponseError) {
	o.Error = &v
}

func (o NewsGet401Response) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Error != nil {
		toSerialize["error"] = o.Error
	}
	return json.Marshal(toSerialize)
}

type NullableNewsGet401Response struct {
	value *NewsGet401Response
	isSet bool
}

func (v NullableNewsGet401Response) Get() *NewsGet401Response {
	return v.value
}

func (v *NullableNewsGet401Response) Set(val *NewsGet401Response) {
	v.value = val
	v.isSet = true
}

func (v NullableNewsGet401Response) IsSet() bool {
	return v.isSet
}

func (v *NullableNewsGet401Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNewsGet401Response(val *NewsGet401Response) *NullableNewsGet401Response {
	return &NullableNewsGet401Response{value: val, isSet: true}
}

func (v NullableNewsGet401Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNewsGet401Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
