/*
Boost API

This is a REST API of the Boost App.

API version: 0.0.1-beta1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
)

// RelatedLinks struct for RelatedLinks
type RelatedLinks struct {
	// The self link of the resource
	Self string `json:"self"`
	// The related link of the resource (might think of it as of parent link)
	Related string `json:"related"`
}

// NewRelatedLinks instantiates a new RelatedLinks object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRelatedLinks(self string, related string) *RelatedLinks {
	this := RelatedLinks{}
	this.Self = self
	this.Related = related
	return &this
}

// NewRelatedLinksWithDefaults instantiates a new RelatedLinks object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRelatedLinksWithDefaults() *RelatedLinks {
	this := RelatedLinks{}
	return &this
}

// GetSelf returns the Self field value
func (o *RelatedLinks) GetSelf() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Self
}

// GetSelfOk returns a tuple with the Self field value
// and a boolean to check if the value has been set.
func (o *RelatedLinks) GetSelfOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Self, true
}

// SetSelf sets field value
func (o *RelatedLinks) SetSelf(v string) {
	o.Self = v
}

// GetRelated returns the Related field value
func (o *RelatedLinks) GetRelated() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Related
}

// GetRelatedOk returns a tuple with the Related field value
// and a boolean to check if the value has been set.
func (o *RelatedLinks) GetRelatedOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Related, true
}

// SetRelated sets field value
func (o *RelatedLinks) SetRelated(v string) {
	o.Related = v
}

func (o RelatedLinks) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["self"] = o.Self
	}
	if true {
		toSerialize["related"] = o.Related
	}
	return json.Marshal(toSerialize)
}

type NullableRelatedLinks struct {
	value *RelatedLinks
	isSet bool
}

func (v NullableRelatedLinks) Get() *RelatedLinks {
	return v.value
}

func (v *NullableRelatedLinks) Set(val *RelatedLinks) {
	v.value = val
	v.isSet = true
}

func (v NullableRelatedLinks) IsSet() bool {
	return v.isSet
}

func (v *NullableRelatedLinks) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRelatedLinks(val *RelatedLinks) *NullableRelatedLinks {
	return &NullableRelatedLinks{value: val, isSet: true}
}

func (v NullableRelatedLinks) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRelatedLinks) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
