/*
Boost API

This is a REST API of the Boost App.

API version: 0.0.1-beta1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
)

// AddEmailRelationships struct for AddEmailRelationships
type AddEmailRelationships struct {
	User AddEmailRelationshipsUser `json:"user"`
}

// NewAddEmailRelationships instantiates a new AddEmailRelationships object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddEmailRelationships(user AddEmailRelationshipsUser) *AddEmailRelationships {
	this := AddEmailRelationships{}
	this.User = user
	return &this
}

// NewAddEmailRelationshipsWithDefaults instantiates a new AddEmailRelationships object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddEmailRelationshipsWithDefaults() *AddEmailRelationships {
	this := AddEmailRelationships{}
	return &this
}

// GetUser returns the User field value
func (o *AddEmailRelationships) GetUser() AddEmailRelationshipsUser {
	if o == nil {
		var ret AddEmailRelationshipsUser
		return ret
	}

	return o.User
}

// GetUserOk returns a tuple with the User field value
// and a boolean to check if the value has been set.
func (o *AddEmailRelationships) GetUserOk() (*AddEmailRelationshipsUser, bool) {
	if o == nil {
		return nil, false
	}
	return &o.User, true
}

// SetUser sets field value
func (o *AddEmailRelationships) SetUser(v AddEmailRelationshipsUser) {
	o.User = v
}

func (o AddEmailRelationships) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["user"] = o.User
	}
	return json.Marshal(toSerialize)
}

type NullableAddEmailRelationships struct {
	value *AddEmailRelationships
	isSet bool
}

func (v NullableAddEmailRelationships) Get() *AddEmailRelationships {
	return v.value
}

func (v *NullableAddEmailRelationships) Set(val *AddEmailRelationships) {
	v.value = val
	v.isSet = true
}

func (v NullableAddEmailRelationships) IsSet() bool {
	return v.isSet
}

func (v *NullableAddEmailRelationships) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddEmailRelationships(val *AddEmailRelationships) *NullableAddEmailRelationships {
	return &NullableAddEmailRelationships{value: val, isSet: true}
}

func (v NullableAddEmailRelationships) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddEmailRelationships) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
