/*
Boost API

This is a REST API of the Boost App.

API version: 0.0.1-beta1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
)

// CredentialsAttributes struct for CredentialsAttributes
type CredentialsAttributes struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// NewCredentialsAttributes instantiates a new CredentialsAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCredentialsAttributes(email string, password string) *CredentialsAttributes {
	this := CredentialsAttributes{}
	this.Email = email
	this.Password = password
	return &this
}

// NewCredentialsAttributesWithDefaults instantiates a new CredentialsAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCredentialsAttributesWithDefaults() *CredentialsAttributes {
	this := CredentialsAttributes{}
	return &this
}

// GetEmail returns the Email field value
func (o *CredentialsAttributes) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *CredentialsAttributes) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *CredentialsAttributes) SetEmail(v string) {
	o.Email = v
}

// GetPassword returns the Password field value
func (o *CredentialsAttributes) GetPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Password
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
func (o *CredentialsAttributes) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Password, true
}

// SetPassword sets field value
func (o *CredentialsAttributes) SetPassword(v string) {
	o.Password = v
}

func (o CredentialsAttributes) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["email"] = o.Email
	}
	if true {
		toSerialize["password"] = o.Password
	}
	return json.Marshal(toSerialize)
}

type NullableCredentialsAttributes struct {
	value *CredentialsAttributes
	isSet bool
}

func (v NullableCredentialsAttributes) Get() *CredentialsAttributes {
	return v.value
}

func (v *NullableCredentialsAttributes) Set(val *CredentialsAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableCredentialsAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableCredentialsAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCredentialsAttributes(val *CredentialsAttributes) *NullableCredentialsAttributes {
	return &NullableCredentialsAttributes{value: val, isSet: true}
}

func (v NullableCredentialsAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCredentialsAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
