/*
Boost API

This is a REST API of the Boost App.

API version: 0.0.1-beta1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
)

// NewsGet403Response struct for NewsGet403Response
type NewsGet403Response struct {
	Error *NewsGet403ResponseError `json:"error,omitempty"`
}

// NewNewsGet403Response instantiates a new NewsGet403Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNewsGet403Response() *NewsGet403Response {
	this := NewsGet403Response{}
	return &this
}

// NewNewsGet403ResponseWithDefaults instantiates a new NewsGet403Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNewsGet403ResponseWithDefaults() *NewsGet403Response {
	this := NewsGet403Response{}
	return &this
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *NewsGet403Response) GetError() NewsGet403ResponseError {
	if o == nil || o.Error == nil {
		var ret NewsGet403ResponseError
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NewsGet403Response) GetErrorOk() (*NewsGet403ResponseError, bool) {
	if o == nil || o.Error == nil {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *NewsGet403Response) HasError() bool {
	if o != nil && o.Error != nil {
		return true
	}

	return false
}

// SetError gets a reference to the given NewsGet403ResponseError and assigns it to the Error field.
func (o *NewsGet403Response) SetError(v NewsGet403ResponseError) {
	o.Error = &v
}

func (o NewsGet403Response) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Error != nil {
		toSerialize["error"] = o.Error
	}
	return json.Marshal(toSerialize)
}

type NullableNewsGet403Response struct {
	value *NewsGet403Response
	isSet bool
}

func (v NullableNewsGet403Response) Get() *NewsGet403Response {
	return v.value
}

func (v *NullableNewsGet403Response) Set(val *NewsGet403Response) {
	v.value = val
	v.isSet = true
}

func (v NullableNewsGet403Response) IsSet() bool {
	return v.isSet
}

func (v *NullableNewsGet403Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNewsGet403Response(val *NewsGet403Response) *NullableNewsGet403Response {
	return &NullableNewsGet403Response{value: val, isSet: true}
}

func (v NullableNewsGet403Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNewsGet403Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
