/*
Boost API

This is a REST API of the Boost App.

API version: 0.0.1-beta1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
)

// AuthPost200Response struct for AuthPost200Response
type AuthPost200Response struct {
	Data TokenPair `json:"data"`
}

// NewAuthPost200Response instantiates a new AuthPost200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthPost200Response(data TokenPair) *AuthPost200Response {
	this := AuthPost200Response{}
	this.Data = data
	return &this
}

// NewAuthPost200ResponseWithDefaults instantiates a new AuthPost200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthPost200ResponseWithDefaults() *AuthPost200Response {
	this := AuthPost200Response{}
	return &this
}

// GetData returns the Data field value
func (o *AuthPost200Response) GetData() TokenPair {
	if o == nil {
		var ret TokenPair
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *AuthPost200Response) GetDataOk() (*TokenPair, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *AuthPost200Response) SetData(v TokenPair) {
	o.Data = v
}

func (o AuthPost200Response) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableAuthPost200Response struct {
	value *AuthPost200Response
	isSet bool
}

func (v NullableAuthPost200Response) Get() *AuthPost200Response {
	return v.value
}

func (v *NullableAuthPost200Response) Set(val *AuthPost200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthPost200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthPost200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthPost200Response(val *AuthPost200Response) *NullableAuthPost200Response {
	return &NullableAuthPost200Response{value: val, isSet: true}
}

func (v NullableAuthPost200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthPost200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
