/*
Boost API

This is a REST API of the Boost App.

API version: 0.0.1-beta1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
)

// UsersIdGet200Response struct for UsersIdGet200Response
type UsersIdGet200Response struct {
	Status   *Status                        `json:"status,omitempty"`
	Meta     map[string]interface{}         `json:"meta,omitempty"`
	Errors   []Error                        `json:"errors,omitempty"`
	Data     User                           `json:"data"`
	Included *UsersIdGet200ResponseIncluded `json:"included,omitempty"`
}

// NewUsersIdGet200Response instantiates a new UsersIdGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUsersIdGet200Response(data User) *UsersIdGet200Response {
	this := UsersIdGet200Response{}
	this.Data = data
	return &this
}

// NewUsersIdGet200ResponseWithDefaults instantiates a new UsersIdGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUsersIdGet200ResponseWithDefaults() *UsersIdGet200Response {
	this := UsersIdGet200Response{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *UsersIdGet200Response) GetStatus() Status {
	if o == nil || o.Status == nil {
		var ret Status
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UsersIdGet200Response) GetStatusOk() (*Status, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *UsersIdGet200Response) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given Status and assigns it to the Status field.
func (o *UsersIdGet200Response) SetStatus(v Status) {
	o.Status = &v
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *UsersIdGet200Response) GetMeta() map[string]interface{} {
	if o == nil || o.Meta == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UsersIdGet200Response) GetMetaOk() (map[string]interface{}, bool) {
	if o == nil || o.Meta == nil {
		return nil, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *UsersIdGet200Response) HasMeta() bool {
	if o != nil && o.Meta != nil {
		return true
	}

	return false
}

// SetMeta gets a reference to the given map[string]interface{} and assigns it to the Meta field.
func (o *UsersIdGet200Response) SetMeta(v map[string]interface{}) {
	o.Meta = v
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *UsersIdGet200Response) GetErrors() []Error {
	if o == nil || o.Errors == nil {
		var ret []Error
		return ret
	}
	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UsersIdGet200Response) GetErrorsOk() ([]Error, bool) {
	if o == nil || o.Errors == nil {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *UsersIdGet200Response) HasErrors() bool {
	if o != nil && o.Errors != nil {
		return true
	}

	return false
}

// SetErrors gets a reference to the given []Error and assigns it to the Errors field.
func (o *UsersIdGet200Response) SetErrors(v []Error) {
	o.Errors = v
}

// GetData returns the Data field value
func (o *UsersIdGet200Response) GetData() User {
	if o == nil {
		var ret User
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *UsersIdGet200Response) GetDataOk() (*User, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *UsersIdGet200Response) SetData(v User) {
	o.Data = v
}

// GetIncluded returns the Included field value if set, zero value otherwise.
func (o *UsersIdGet200Response) GetIncluded() UsersIdGet200ResponseIncluded {
	if o == nil || o.Included == nil {
		var ret UsersIdGet200ResponseIncluded
		return ret
	}
	return *o.Included
}

// GetIncludedOk returns a tuple with the Included field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UsersIdGet200Response) GetIncludedOk() (*UsersIdGet200ResponseIncluded, bool) {
	if o == nil || o.Included == nil {
		return nil, false
	}
	return o.Included, true
}

// HasIncluded returns a boolean if a field has been set.
func (o *UsersIdGet200Response) HasIncluded() bool {
	if o != nil && o.Included != nil {
		return true
	}

	return false
}

// SetIncluded gets a reference to the given UsersIdGet200ResponseIncluded and assigns it to the Included field.
func (o *UsersIdGet200Response) SetIncluded(v UsersIdGet200ResponseIncluded) {
	o.Included = &v
}

func (o UsersIdGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Status != nil {
		toSerialize["status"] = o.Status
	}
	if o.Meta != nil {
		toSerialize["meta"] = o.Meta
	}
	if o.Errors != nil {
		toSerialize["errors"] = o.Errors
	}
	if true {
		toSerialize["data"] = o.Data
	}
	if o.Included != nil {
		toSerialize["included"] = o.Included
	}
	return json.Marshal(toSerialize)
}

type NullableUsersIdGet200Response struct {
	value *UsersIdGet200Response
	isSet bool
}

func (v NullableUsersIdGet200Response) Get() *UsersIdGet200Response {
	return v.value
}

func (v *NullableUsersIdGet200Response) Set(val *UsersIdGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableUsersIdGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableUsersIdGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUsersIdGet200Response(val *UsersIdGet200Response) *NullableUsersIdGet200Response {
	return &NullableUsersIdGet200Response{value: val, isSet: true}
}

func (v NullableUsersIdGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUsersIdGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
