/*
Boost API

This is a REST API of the Boost App.

API version: 0.0.1-beta1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
)

// EmailRelationships struct for EmailRelationships
type EmailRelationships struct {
	User EmailRelationshipsUser `json:"user"`
}

// NewEmailRelationships instantiates a new EmailRelationships object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmailRelationships(user EmailRelationshipsUser) *EmailRelationships {
	this := EmailRelationships{}
	this.User = user
	return &this
}

// NewEmailRelationshipsWithDefaults instantiates a new EmailRelationships object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmailRelationshipsWithDefaults() *EmailRelationships {
	this := EmailRelationships{}
	return &this
}

// GetUser returns the User field value
func (o *EmailRelationships) GetUser() EmailRelationshipsUser {
	if o == nil {
		var ret EmailRelationshipsUser
		return ret
	}

	return o.User
}

// GetUserOk returns a tuple with the User field value
// and a boolean to check if the value has been set.
func (o *EmailRelationships) GetUserOk() (*EmailRelationshipsUser, bool) {
	if o == nil {
		return nil, false
	}
	return &o.User, true
}

// SetUser sets field value
func (o *EmailRelationships) SetUser(v EmailRelationshipsUser) {
	o.User = v
}

func (o EmailRelationships) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["user"] = o.User
	}
	return json.Marshal(toSerialize)
}

type NullableEmailRelationships struct {
	value *EmailRelationships
	isSet bool
}

func (v NullableEmailRelationships) Get() *EmailRelationships {
	return v.value
}

func (v *NullableEmailRelationships) Set(val *EmailRelationships) {
	v.value = val
	v.isSet = true
}

func (v NullableEmailRelationships) IsSet() bool {
	return v.isSet
}

func (v *NullableEmailRelationships) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmailRelationships(val *EmailRelationships) *NullableEmailRelationships {
	return &NullableEmailRelationships{value: val, isSet: true}
}

func (v NullableEmailRelationships) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmailRelationships) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
