/*
Boost API

This is a REST API of the Boost App.

API version: 0.0.1-beta1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
)

// TokenPairAttributes struct for TokenPairAttributes
type TokenPairAttributes struct {
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
}

// NewTokenPairAttributes instantiates a new TokenPairAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTokenPairAttributes(accessToken string, refreshToken string) *TokenPairAttributes {
	this := TokenPairAttributes{}
	this.AccessToken = accessToken
	this.RefreshToken = refreshToken
	return &this
}

// NewTokenPairAttributesWithDefaults instantiates a new TokenPairAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTokenPairAttributesWithDefaults() *TokenPairAttributes {
	this := TokenPairAttributes{}
	return &this
}

// GetAccessToken returns the AccessToken field value
func (o *TokenPairAttributes) GetAccessToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccessToken
}

// GetAccessTokenOk returns a tuple with the AccessToken field value
// and a boolean to check if the value has been set.
func (o *TokenPairAttributes) GetAccessTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccessToken, true
}

// SetAccessToken sets field value
func (o *TokenPairAttributes) SetAccessToken(v string) {
	o.AccessToken = v
}

// GetRefreshToken returns the RefreshToken field value
func (o *TokenPairAttributes) GetRefreshToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RefreshToken
}

// GetRefreshTokenOk returns a tuple with the RefreshToken field value
// and a boolean to check if the value has been set.
func (o *TokenPairAttributes) GetRefreshTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RefreshToken, true
}

// SetRefreshToken sets field value
func (o *TokenPairAttributes) SetRefreshToken(v string) {
	o.RefreshToken = v
}

func (o TokenPairAttributes) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["access_token"] = o.AccessToken
	}
	if true {
		toSerialize["refresh_token"] = o.RefreshToken
	}
	return json.Marshal(toSerialize)
}

type NullableTokenPairAttributes struct {
	value *TokenPairAttributes
	isSet bool
}

func (v NullableTokenPairAttributes) Get() *TokenPairAttributes {
	return v.value
}

func (v *NullableTokenPairAttributes) Set(val *TokenPairAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableTokenPairAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableTokenPairAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTokenPairAttributes(val *TokenPairAttributes) *NullableTokenPairAttributes {
	return &NullableTokenPairAttributes{value: val, isSet: true}
}

func (v NullableTokenPairAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTokenPairAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
