/*
Boost API

This is a REST API of the Boost App.

API version: 0.0.1-beta1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
)

// AddUser struct for AddUser
type AddUser struct {
	Type       EntityType        `json:"type"`
	Attributes AddUserAttributes `json:"attributes"`
}

// NewAddUser instantiates a new AddUser object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddUser(type_ EntityType, attributes AddUserAttributes) *AddUser {
	this := AddUser{}
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewAddUserWithDefaults instantiates a new AddUser object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddUserWithDefaults() *AddUser {
	this := AddUser{}
	return &this
}

// GetType returns the Type field value
func (o *AddUser) GetType() EntityType {
	if o == nil {
		var ret EntityType
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *AddUser) GetTypeOk() (*EntityType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *AddUser) SetType(v EntityType) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *AddUser) GetAttributes() AddUserAttributes {
	if o == nil {
		var ret AddUserAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *AddUser) GetAttributesOk() (*AddUserAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *AddUser) SetAttributes(v AddUserAttributes) {
	o.Attributes = v
}

func (o AddUser) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["type"] = o.Type
	}
	if true {
		toSerialize["attributes"] = o.Attributes
	}
	return json.Marshal(toSerialize)
}

type NullableAddUser struct {
	value *AddUser
	isSet bool
}

func (v NullableAddUser) Get() *AddUser {
	return v.value
}

func (v *NullableAddUser) Set(val *AddUser) {
	v.value = val
	v.isSet = true
}

func (v NullableAddUser) IsSet() bool {
	return v.isSet
}

func (v *NullableAddUser) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddUser(val *AddUser) *NullableAddUser {
	return &NullableAddUser{value: val, isSet: true}
}

func (v NullableAddUser) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddUser) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
