/*
Boost API

This is a REST API of the Boost App.

API version: 0.0.1-beta1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
)

// NewsGet201Response struct for NewsGet201Response
type NewsGet201Response struct {
	Status *Status `json:"status,omitempty"`
	Data   *News   `json:"data,omitempty"`
}

// NewNewsGet201Response instantiates a new NewsGet201Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNewsGet201Response() *NewsGet201Response {
	this := NewsGet201Response{}
	return &this
}

// NewNewsGet201ResponseWithDefaults instantiates a new NewsGet201Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNewsGet201ResponseWithDefaults() *NewsGet201Response {
	this := NewsGet201Response{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *NewsGet201Response) GetStatus() Status {
	if o == nil || o.Status == nil {
		var ret Status
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NewsGet201Response) GetStatusOk() (*Status, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *NewsGet201Response) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given Status and assigns it to the Status field.
func (o *NewsGet201Response) SetStatus(v Status) {
	o.Status = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *NewsGet201Response) GetData() News {
	if o == nil || o.Data == nil {
		var ret News
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NewsGet201Response) GetDataOk() (*News, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *NewsGet201Response) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given News and assigns it to the Data field.
func (o *NewsGet201Response) SetData(v News) {
	o.Data = &v
}

func (o NewsGet201Response) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Status != nil {
		toSerialize["status"] = o.Status
	}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableNewsGet201Response struct {
	value *NewsGet201Response
	isSet bool
}

func (v NullableNewsGet201Response) Get() *NewsGet201Response {
	return v.value
}

func (v *NullableNewsGet201Response) Set(val *NewsGet201Response) {
	v.value = val
	v.isSet = true
}

func (v NullableNewsGet201Response) IsSet() bool {
	return v.isSet
}

func (v *NullableNewsGet201Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNewsGet201Response(val *NewsGet201Response) *NullableNewsGet201Response {
	return &NullableNewsGet201Response{value: val, isSet: true}
}

func (v NullableNewsGet201Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNewsGet201Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
