/*
Boost API

This is a REST API of the Boost App.

API version: 0.0.1-beta1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
)

// NewsAddPost400Response struct for NewsAddPost400Response
type NewsAddPost400Response struct {
	Error *Status `json:"error,omitempty"`
}

// NewNewsAddPost400Response instantiates a new NewsAddPost400Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNewsAddPost400Response() *NewsAddPost400Response {
	this := NewsAddPost400Response{}
	return &this
}

// NewNewsAddPost400ResponseWithDefaults instantiates a new NewsAddPost400Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNewsAddPost400ResponseWithDefaults() *NewsAddPost400Response {
	this := NewsAddPost400Response{}
	return &this
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *NewsAddPost400Response) GetError() Status {
	if o == nil || o.Error == nil {
		var ret Status
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NewsAddPost400Response) GetErrorOk() (*Status, bool) {
	if o == nil || o.Error == nil {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *NewsAddPost400Response) HasError() bool {
	if o != nil && o.Error != nil {
		return true
	}

	return false
}

// SetError gets a reference to the given Status and assigns it to the Error field.
func (o *NewsAddPost400Response) SetError(v Status) {
	o.Error = &v
}

func (o NewsAddPost400Response) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Error != nil {
		toSerialize["error"] = o.Error
	}
	return json.Marshal(toSerialize)
}

type NullableNewsAddPost400Response struct {
	value *NewsAddPost400Response
	isSet bool
}

func (v NullableNewsAddPost400Response) Get() *NewsAddPost400Response {
	return v.value
}

func (v *NullableNewsAddPost400Response) Set(val *NewsAddPost400Response) {
	v.value = val
	v.isSet = true
}

func (v NullableNewsAddPost400Response) IsSet() bool {
	return v.isSet
}

func (v *NullableNewsAddPost400Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNewsAddPost400Response(val *NewsAddPost400Response) *NullableNewsAddPost400Response {
	return &NullableNewsAddPost400Response{value: val, isSet: true}
}

func (v NullableNewsAddPost400Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNewsAddPost400Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
