/*
Boost API

This is a REST API of the Boost App.

API version: 0.0.1-beta1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
)

// EmailRelationshipsUser User that owns this email.
type EmailRelationshipsUser struct {
	Links *RelatedLinks  `json:"links,omitempty"`
	Data  *RelatedEntity `json:"data,omitempty"`
}

// NewEmailRelationshipsUser instantiates a new EmailRelationshipsUser object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmailRelationshipsUser() *EmailRelationshipsUser {
	this := EmailRelationshipsUser{}
	return &this
}

// NewEmailRelationshipsUserWithDefaults instantiates a new EmailRelationshipsUser object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmailRelationshipsUserWithDefaults() *EmailRelationshipsUser {
	this := EmailRelationshipsUser{}
	return &this
}

// GetLinks returns the Links field value if set, zero value otherwise.
func (o *EmailRelationshipsUser) GetLinks() RelatedLinks {
	if o == nil || o.Links == nil {
		var ret RelatedLinks
		return ret
	}
	return *o.Links
}

// GetLinksOk returns a tuple with the Links field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailRelationshipsUser) GetLinksOk() (*RelatedLinks, bool) {
	if o == nil || o.Links == nil {
		return nil, false
	}
	return o.Links, true
}

// HasLinks returns a boolean if a field has been set.
func (o *EmailRelationshipsUser) HasLinks() bool {
	if o != nil && o.Links != nil {
		return true
	}

	return false
}

// SetLinks gets a reference to the given RelatedLinks and assigns it to the Links field.
func (o *EmailRelationshipsUser) SetLinks(v RelatedLinks) {
	o.Links = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *EmailRelationshipsUser) GetData() RelatedEntity {
	if o == nil || o.Data == nil {
		var ret RelatedEntity
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailRelationshipsUser) GetDataOk() (*RelatedEntity, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *EmailRelationshipsUser) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given RelatedEntity and assigns it to the Data field.
func (o *EmailRelationshipsUser) SetData(v RelatedEntity) {
	o.Data = &v
}

func (o EmailRelationshipsUser) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Links != nil {
		toSerialize["links"] = o.Links
	}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableEmailRelationshipsUser struct {
	value *EmailRelationshipsUser
	isSet bool
}

func (v NullableEmailRelationshipsUser) Get() *EmailRelationshipsUser {
	return v.value
}

func (v *NullableEmailRelationshipsUser) Set(val *EmailRelationshipsUser) {
	v.value = val
	v.isSet = true
}

func (v NullableEmailRelationshipsUser) IsSet() bool {
	return v.isSet
}

func (v *NullableEmailRelationshipsUser) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmailRelationshipsUser(val *EmailRelationshipsUser) *NullableEmailRelationshipsUser {
	return &NullableEmailRelationshipsUser{value: val, isSet: true}
}

func (v NullableEmailRelationshipsUser) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmailRelationshipsUser) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
