/*
Boost API

This is a REST API of the Boost App.

API version: 0.0.1-beta1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
)

// UserRelationshipsEmails Emails that belong to this user.
type UserRelationshipsEmails struct {
	Data []RelatedEntity `json:"data,omitempty"`
}

// NewUserRelationshipsEmails instantiates a new UserRelationshipsEmails object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserRelationshipsEmails() *UserRelationshipsEmails {
	this := UserRelationshipsEmails{}
	return &this
}

// NewUserRelationshipsEmailsWithDefaults instantiates a new UserRelationshipsEmails object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserRelationshipsEmailsWithDefaults() *UserRelationshipsEmails {
	this := UserRelationshipsEmails{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *UserRelationshipsEmails) GetData() []RelatedEntity {
	if o == nil || o.Data == nil {
		var ret []RelatedEntity
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserRelationshipsEmails) GetDataOk() ([]RelatedEntity, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *UserRelationshipsEmails) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given []RelatedEntity and assigns it to the Data field.
func (o *UserRelationshipsEmails) SetData(v []RelatedEntity) {
	o.Data = v
}

func (o UserRelationshipsEmails) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableUserRelationshipsEmails struct {
	value *UserRelationshipsEmails
	isSet bool
}

func (v NullableUserRelationshipsEmails) Get() *UserRelationshipsEmails {
	return v.value
}

func (v *NullableUserRelationshipsEmails) Set(val *UserRelationshipsEmails) {
	v.value = val
	v.isSet = true
}

func (v NullableUserRelationshipsEmails) IsSet() bool {
	return v.isSet
}

func (v *NullableUserRelationshipsEmails) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserRelationshipsEmails(val *UserRelationshipsEmails) *NullableUserRelationshipsEmails {
	return &NullableUserRelationshipsEmails{value: val, isSet: true}
}

func (v NullableUserRelationshipsEmails) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserRelationshipsEmails) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
