openapi: 3.0.0
info:
  title: Boost API
  description: This is a REST API of the Boost App.
  version: 0.0.1-beta1
servers:
  - url: http://api.boost.com.ua/v1
    description: Main (production) server
  - url: http://dev.api.boost.com.ua
    description: Test (development) server
paths:
  /healthcheck:
    get:
      summary: Returns success if server runs successfully.
      responses:
        '200':  # status code
          description: A JSON object with healthcheck result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: A JSON object with healthcheck result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
          example: 200
        message:
          type: string
          example: 'Server runs successfully'